name: CI

on:
  push:
  pull_request:

env:
  GIT_EMAIL: ci@mail
  GIT_NAME: ci

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        oscript_version: ['1.2.0', 'dev', 'stable']

    steps:
    - uses: actions/checkout@v2

    - name: Setup Onescript Action
      uses: otymko/setup-onescript@v1.0
      with:
        version: ${{ matrix.oscript_version }}

    - name: Install dependencies
      run: |
        opm install opm@1.0.0
        opm install -l --dev

    # Runs a set of commands using the runners shell
    - name: Run tests
      run: |
        oscript ./tasks/coverage.os
